# Generated by Django 5.0.1 on 2025-01-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramusers',
            options={'verbose_name': 'Telegram user', 'verbose_name_plural': 'Telegram users'},
        ),
    ]
