# Generated by Django 5.0.1 on 2025-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_alter_telegramusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramusers',
            options={'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Чат ID'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='city',
            field=models.CharField(default='Toshkent', max_length=20, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский')], default='uz', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
