# Generated by Django 5.0.1 on 2025-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spareparts',
            options={'verbose_name': 'Запасная часть', 'verbose_name_plural': 'Запасные части'},
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (на узбекском)'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='ru_name',
            field=models.CharField(max_length=100, verbose_name='Название (на русском)'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
