# Generated by Django 5.0.1 on 2025-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brands_options_alter_brands_category_and_more'),
        ('contacts', '0001_initial'),
        ('spare_parts', '0002_alter_spareparts_options_alter_spareparts_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='landmark_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ориентир (на русском)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='brands',
            field=models.ManyToManyField(related_name='contacts', to='brands.brands', verbose_name='Бренды'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ориентир (на узбекском)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='spare_parts',
            field=models.ManyToManyField(related_name='contacts', to='spare_parts.spareparts', verbose_name='Запасные части'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
