# Generated by Django 5.0.1 on 2025-01-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('yengil mashina', 'Yengil mashina'), ('yuk mashinasi', 'Yuk mashinasi'), ('maxsus jihozlar', 'Maxsus jihozlar')], max_length=100)),
                ('ru_category', models.CharField(choices=[('легкая машина ', 'Легкая машина'), ('грузовик', 'Грузовик'), ('специальная техника ', 'Специальная техника ')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
