# Generated by Django 5.0.1 on 2025-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='category',
            field=models.CharField(choices=[('yengil mashina', 'Yengil mashina'), ('yuk mashinasi', 'Yuk mashinasi'), ('maxsus jihozlar', 'Maxsus jihozlar')], max_length=100, verbose_name='Категория (на узбекском)'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='ru_category',
            field=models.CharField(choices=[('легкая машина', 'Легкая машина'), ('грузовик', 'Грузовик'), ('специальная техника', 'Специальная техника')], max_length=100, verbose_name='Категория (на русском)'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
